### ISSUE TITLE
Recent upstream changes in klipper break dwc2-for-klipper

### ISSUE THREAD

**Issue by Athemis** [Stephan3/dwc2-for-klipper#36]
Hi, 
first of all, thanks for this great alternative to octoprint!
A recent upstream commit changes the way how to check whether a motor is enabled or not: https://github.com/KevinOConnor/klipper/commit/0e30b862c7e94a9e259f213dd25ec1671ca560c9

This leads to the following error:
```
Traceback (most recent call last):
  File "/home/pi/klippy-env/local/lib/python2.7/site-packages/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/home/pi/klippy-env/local/lib/python2.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/pi/klippy-env/local/lib/python2.7/site-packages/tornado/concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "/home/pi/klippy-env/local/lib/python2.7/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/home/pi/git/klipper/klippy/extras/web_dwc2.py", line 256, in get
    self.web_dwc2.rr_status_2()
  File "/home/pi/git/klipper/klippy/extras/web_dwc2.py", line 752, in rr_status_2
    "axesHomed": self.get_axes_homed() ,
  File "/home/pi/git/klipper/klippy/extras/web_dwc2.py", line 1364, in get_axes_homed
    if rail.is_motor_enabled():
AttributeError: PrinterRail instance has no attribute 'is_motor_enabled'
```

**Comment by shaiss** [comment]
@Stephan3 I'm having the same issues as @Athemis above.  I updated to the latest klipper and DWC, however still getting similar errors to whats above.  my klippy.log file @ https://drive.google.com/open?id=12a-4pGNgFkNVPSseINP295wbfDpc-Aq0&fbclid=IwAR2aXbjvRN5XhdQC4xszfI7IoDcSyLt-Jfkbfc-SrIo38ArX8BKl_QIH0Xc

Any suggestions would be appriciated.  Thank you!
