### ISSUE TITLE
Clean Install Python Error

### ISSUE THREAD

**Issue by ghost** [Stephan3/dwc2-for-klipper#89]
Hi, I have been having issues getting Klipper and DWC2 to work so I did a clean install and I am getting this error message. I think its a Python 2.7 error but I dont know what to do,

Starting Klippy...
Args: ['/home/pi/klipper/klippy/klippy.py', '/home/pi/printer.cfg', '-l', '/tmp/klippy.log']
Git version: 'v0.8.0-602-g65ae08ef-dirty'
CPU: 4 core ARMv7 Processor rev 4 (v7l)
Python: '2.7.16 (default, Oct 10 2019, 22:02:15) \n[GCC 8.3.0]'
Start printer at Tue Jun 16 16:50:18 2020 (1592292018.3 4428.9)
===== Config file =====
[stepper_x]
step_pin = PC15
dir_pin = PF0
enable_pin = !PF1
step_distance = .0125
endstop_pin = ^!PF2
position_endstop = 0
position_max = 220
homing_speed = 50

[stepper_y]
step_pin = PE3
dir_pin = PE2
enable_pin = !PE4
step_distance = .0125
endstop_pin = ^!PC13
position_endstop = 0
position_max = 250
homing_speed = 50

[stepper_z]
step_pin = PB8
dir_pin = PB7
enable_pin = !PB9
step_distance = .0025
endstop_pin = ^PE0
position_endstop = 0
position_max = 200
homing_speed = 12
second_homing_speed = 1

[stepper_z1]
step_pin = PD1
dir_pin = PD0
enable_pin = !PD2
step_distance = .0025
endstop_pin = ^PD3

[heater_bed]
heater_pin = PA2
sensor_pin = PC0
sensor_type = ATC Semitec 104GT-2
control = watermark
min_temp = 0
max_temp = 130

[fan]
pin = PE5

[heater_fan fan1]
pin = PE6

[mcu]
serial = /dev/serial/by-id/usb-Klipper_stm32f407xx_3A0034000D51373431393537-if00

[printer]
kinematics = corexy
max_velocity = 500
max_accel = 3000
max_z_velocity = 12
max_z_accel = 5

[web_dwc2]
printer_name = Stefan Asmus
listen_adress = 0.0.0.0
listen_port = 4750
web_path = dwc2/web
=======================
Unhandled exception during connect
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/klippy.py", line 136, in _connect
    self._read_config()
  File "/home/pi/klipper/klippy/klippy.py", line 129, in _read_config
    self.load_object(config, section_config.get_name(), None)
  File "/home/pi/klipper/klippy/klippy.py", line 118, in load_object
    self.objects[section] = init_func(config.getsection(section))
  File "/home/pi/klipper/klippy/extras/web_dwc2.py", line 1684, in load_config
    return web_dwc2(config)
  File "/home/pi/klipper/klippy/extras/web_dwc2.py", line 63, in __init__
    self.sdpath = os.path.normpath(os.path.expanduser(self.sdpath))
  File "/home/pi/klippy-env/lib/python2.7/posixpath.py", line 254, in expanduser
    if not path.startswith('~'):
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by ghost** [comment]
Installed OctoPrint.
